version: '3.8'
services:
  backend:
    build: ./ai-on-fhir-backend
    ports:
      - "5000:5000"
  frontend:
    build: ./ai-on-fhir-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
